name: Build Apache HTTPD

on:
  push:
    paths:
      - '**.yml'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        repository: openssl/openssl
        ref: openssl-3.1.3
    
    - name: Cache OpenSSL build
      id: cache-openssl
      uses: actions/cache@v2
      with:
        path: C:\openssl
        key: ${{ runner.os }}-openssl-${{ hashFiles('**/openssl/*.yml') }}
        restore-keys: |
          ${{ runner.os }}-openssl-

    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Set up NASM
      uses: ilammy/setup-nasm@v1.4.0

    - name: Configure OpenSSL
      run: |
        perl Configure VC-WIN64A --prefix=C:\openssl

    - name: Build OpenSSL
      run: |
        nmake
        nmake test
        nmake install

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: openssl-windows
        path: C:\openssl

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')"
      id: extract_branch

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.extract_branch.outputs.branch }}
        release_name: Release ${{ steps.extract_branch.outputs.branch }}
        draft: false
        prerelease: false

    # - name: Create Release
    #   id: create_release
    #   uses: actions/create-release@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     tag_name: ${{ github.ref }}
    #     release_name: Release ${{ github.ref }}
    #     draft: false
    #     prerelease: false
    - name: Zip artifacts
      run: Compress-Archive -Path C:\openssl -DestinationPath openssl-windows.zip

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: openssl-windows.zip
        asset_name: openssl-windows.zip
        asset_content_type: application/zip

    # - name: Upload Release Asset
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     upload_url: ${{ steps.create_release.outputs.upload_url }}
    #     asset_path: C:\openssl
    #     asset_name: openssl-windows.zip
    #     asset_content_type: application/zip
