name: Build Apache HTTPD

on:
  push:
    # branches:
    #   - master
    paths:
      - '**.yml'

yaml
Copy code
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: openssl/openssl
        ref: OpenSSL_1_1_1-stable

    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install NASM
      run: |
        choco install nasm

    - name: Configure OpenSSL
      run: |
        perl Configure VC-WIN32 --prefix=C:\openssl

    - name: Build OpenSSL
      run: |
        nmake
        nmake test
        nmake install

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: openssl-windows
        path: |
          C:\openssl
