name: Build Apache HTTPD

on:
  push:
    paths:
      - '**.yml'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        repository: openssl/openssl
        ref: openssl-3.1.3
    
    - name: Cache OpenSSL build
      id: cache-openssl
      uses: actions/cache@v2
      with:
        path: C:\openssl
        key: ${{ runner.os }}-openssl-${{ hashFiles('**/openssl/*.yml') }}
        restore-keys: |
          ${{ runner.os }}-openssl-

    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Set up NASM
      uses: ilammy/setup-nasm@v1.4.0

    - name: Configure OpenSSL
      run: |
        perl Configure VC-WIN64A --prefix=C:\openssl

    - name: Build OpenSSL
      run: |
        nmake
        nmake test
        nmake install

    - name: Zip OpenSSL build
      run: |
        Compress-Archive -Path C:\openssl -DestinationPath openssl.zip

    - name: Create ZIP Archive
      run: |
        Compress-Archive -Path C:\openssl -DestinationPath C:\openssl.zip
      shell: powershell

    - name: Move ZIP Archive to Repository Directory
      run: |
        Move-Item -Path 'C:\openssl.zip' -Destination "$Env:GITHUB_WORKSPACE\openssl.zip"
      shell: powershell

    - name: Commit and Push ZIP Archive
      run: |
        git config user.name "Your Name"
        git config user.email "your@email.com"
        git add C:\openssl.zip
        git commit -m "Add OpenSSL ZIP archive"
        git push
      shell: powershell
