name: Build Apache HTTPD

on:
  push:
    # branches:
    #   - master
    paths:
      - '**.yml'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Apache HTTPD code
      uses: actions/checkout@v2
      with:
        repository: apache/httpd
        ref: 'trunk'

    - name: Install Scoop
      run: |
        iwr -useb get.scoop.sh | iex
        
    - name: Install dependencies
      run: |
        scoop install perl
        scoop install nasm
        scoop install gawk
        scoop install patch
        scoop install diffutils

    - name: Build
      run: |
        cd srclib\apr
        nmake /f Makefile.win buildall
        cd ..\apr-iconv
        nmake /f Makefile.win buildall
        cd ..\apr-util
        nmake /f Makefile.win buildall
        cd ..\..
        nmake /f Makefile.win buildall

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: httpd-build
        path: |
          **/Release/*.dll
          **/Release/*.exe
