name: Build Apache HTTPD

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Apache HTTPD code
      uses: actions/checkout@v2
      with:
        repository: apache/httpd
        ref: 'trunk'

    - name: Install dependencies
      run: |
        choco install -y perl activeperl
        choco install -y nasm
        choco install -y awk
        choco install -y patch
        choco install -y diffutils

    - name: Build
      run: |
        cd srclib\apr
        nmake /f Makefile.win buildall
        cd ..\apr-iconv
        nmake /f Makefile.win buildall
        cd ..\apr-util
        nmake /f Makefile.win buildall
        cd ..\..
        nmake /f Makefile.win buildall

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: httpd-build
        path: |
          **/Release/*.dll
          **/Release/*.exe
